name: Build and Publish

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build-wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            cflags: "-O3"
          - os: macos-latest
            cflags: "-O3"
          - os: windows-latest
            cflags: "/O2"
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: astral-sh/setup-uv@v6
        with:
          python-version: '3.x'
          enable-cache: true
      - name: Install cibuildwheel
        run: |
          python -m pip install --upgrade pip
          pip install cibuildwheel
      - name: Build wheels
        env:
          CIBW_SKIP: cp36-* cp37-* cp38-* cp39-*
          CIBW_ENVIRONMENT: "CFLAGS='${{ matrix.cflags }}' CXXFLAGS='${{ matrix.cflags }}'"
          CIBW_TEST_COMMAND: "pytest {project}/test"
          CIBW_TEST_REQUIRES: "pytest"
        run: uvx cibuildwheel --output-dir dist
      - uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.os }}
          path: dist/*.whl

  build-sdist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: astral-sh/setup-uv@v6
        with:
          python-version: '3.x'
          enable-cache: true
          cache-dependency-glob: "uv.lock"
      - name: Build sdist
        run: uvx build --sdist --outdir dist
      - uses: actions/upload-artifact@v4
        with:
          name: sdist
          path: dist/*.tar.gz

  publish:
    needs: [build-wheels, build-sdist]
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/prefixtrie
    permissions:
      id-token: write  # For trusted publishing
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          pattern: '*'
          path: dist
          merge-multiple: true
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist
          skip-existing: true
